apiVersion: v1
kind: Namespace
metadata:
  name: develop
  labels:
    name: develop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: vehiclesapp
        resources: 
          limits:
            cpu: "200m"
            memory: "128Mi"
        image: fog2021gr09/vehiclesapp:develop.v.1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-deployment
  namespace: develop
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30001
    targetPort: 3000
  selector:
    app: nodejs

